name: jsjson
description: A platform specialized JSON parser
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  dart_flutter_team_lints: ^2.1.0
  test: ^1.24.0
